# Generated by Django 3.1.3 on 2020-11-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptom',
            name='title',
            field=models.CharField(choices=[('Tab', 'تب'), ('Sar dard', 'سردرد'), ('Sorfe', 'سرفه'), ('Badan dard', 'بدن درد'), ('Tangi nafas', 'تنگی نفس'), ('Khastegi', 'خستگی'), ('Abrizesh bini', 'آبریزش بینی')], max_length=100, null=True),
        ),
    ]
