# Generated by Django 3.1.3 on 2020-11-21 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('آنفولانزا', 'آنفولانزا'), ('مشکوک به کرونا', 'مشکوک به کرونا'), ('قطعی کرونا', 'قطعی کرونا')], max_length=100, null=True)),
                ('probableWeight', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('قرنطینه خانگی', 'قرنطینه خانگی'), ('بستری در بیمارستان', 'بستری در بیمارستان'), ('عادی', 'عادی'), ('فوت شده', 'فوت شده')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('تب', 'تب'), ('سردرد', 'سردرد'), ('سرفه', 'سرفه')], max_length=100, null=True)),
                ('weight', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_date', models.DateField(blank=True, null=True)),
                ('disease_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientapp.diseasestatus')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientapp.patient')),
                ('patient_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientapp.patientstatus')),
            ],
        ),
        migrations.CreateModel(
            name='PatientSymptom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientapp.patient')),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientapp.symptom')),
            ],
        ),
        migrations.CreateModel(
            name='Connections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patientapp.patient')),
            ],
        ),
    ]
