# Generated by Django 3.1.3 on 2020-11-21 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0002_connections_diseasestatus_patientstatus_patientsymptom_status_symptom'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='symptoms',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
