# Generated by Django 3.1.3 on 2020-11-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0002_auto_20201128_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseasestatus',
            name='disease_status_title',
            field=models.CharField(choices=[('آنفولانزا', 'آنفولانزا'), ('مشکوک به کرونا', 'مشکوک به کرونا'), ('قطعی کرونا', 'قطعی کرونا')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patientstatus',
            name='patient_status_title',
            field=models.CharField(choices=[('قرنطینه', 'قرنطینه'), ('بستری در بیمارستان', 'بستری در بیمارستان'), ('عادی', 'عادی'), ('فوت شده', 'فوت شده')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='symptom_title',
            field=models.CharField(choices=[('تب', 'تب'), ('سر درد', 'سر درد'), ('سرفه', 'سرفه'), ('سرفه خشک', 'سرفه خشک'), ('خستگی', 'خستگی'), ('تنگی نفس', 'تنگی نفس'), ('آبریزش بینی', 'آبریزش بینی'), ('گلو درد', 'گلو درد')], max_length=100, null=True),
        ),
    ]
