# Generated by Django 3.1.3 on 2020-11-26 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0002_auto_20201126_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptom',
            name='title',
            field=models.CharField(choices=[('تب', 'تب'), ('سردرد', 'سردرد'), ('سرفه', 'سرفه'), ('بدن درد', 'بدن درد'), ('تنگی نفس', 'تنگی نفس'), ('خستگی', 'خستگی'), ('آبریزش بینی', 'آبریزش بینی')], max_length=100, null=True),
        ),
    ]
