# Generated by Django 3.1.3 on 2020-11-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0003_auto_20201128_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptom',
            name='symptom_title',
            field=models.CharField(choices=[('تب', 'تب'), ('سر درد', 'سر درد'), ('سرفه خشک', 'سرفه خشک'), ('خستگی', 'خستگی'), ('تنگی نفس', 'تنگی نفس'), ('آبریزش بینی', 'آبریزش بینی'), ('گلو درد', 'گلو درد')], max_length=100, null=True),
        ),
    ]
