# Generated by Django 3.1.3 on 2020-11-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0003_auto_20201126_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseasestatus',
            name='is_System',
            field=models.BooleanField(default=False),
        ),
    ]
