# Generated by Django 3.1.3 on 2020-11-21 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0003_patient_symptoms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='symptoms',
        ),
    ]
