# Generated by Django 3.1.3 on 2020-11-26 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0006_auto_20201126_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseasestatus',
            name='title',
            field=models.CharField(choices=[('Anfoolanza', 'Anfoolanza'), ('Mashkook', 'Mashkook'), ('Ghatei', 'Ghatei')], max_length=100, null=True),
        ),
    ]
