# Generated by Django 3.1.3 on 2020-11-26 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0009_auto_20201126_1135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diseasestatus',
            old_name='title',
            new_name='DiseaseStatustitle',
        ),
        migrations.RenameField(
            model_name='status',
            old_name='title',
            new_name='Statustitle',
        ),
    ]
